import ReduxProviders from '@/redux/providers'
import './globals.css'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'

const quicksand = Quicksand({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <ReduxProviders>
          {children}
        </ReduxProviders>
      </body>
    </html>
  )
}
